export { TRAIT_TYPES, traitTypeOf } from './traitType.js';
export type { TraitType } from './traitType.js';
export type { Trait, Catalog } from './trait.js';
export type { ResilientTrait, ADN } from './adn.js';
export { POWER_TEMPLATES } from './pouvoir.js';
export type { Pouvoir, PowerTemplate, PowerKind } from './pouvoir.js';
export { GENRE_TOUT } from './espece.js';
export type { Genre, Espece } from './espece.js';
export type { Personne, Conjoint } from './personne.js';
export type { Couple } from './couple.js';
export type { PopulationEvent } from './event.js';
export { birthEvent, deathEvent, coupleEvent, divorceEvent } from './event.js';
